version: "3.9"

services:
    web: # Django 서비스
      build:
        context: .              # 현재 디렉토리에서 Dockerfile 사용
        dockerfile: Dockerfile
      container_name: django_service
      volumes:
        - ./app:/app            # 로컬 app 폴더 → 컨테이너 /app 에 마운트
      ports:
        - "8000:8000"           # 호스트 8000 → 컨테이너 8000
      depends_on:
        - db                    # db 서비스가 먼저 준비되어야 실행
      command: bash -c "python manage.py runserver 0.0.0.0:8000"
      environment:              # Django에서 DB 연결할 때 참고할 변수들
        - DJANGO_SETTINGS_MODULE=config.settings
        - DB_HOST=db
        - DB_NAME=db_postgres
        - DB_USER=user_postgres
        - DB_PASSWORD=pwd_postgres

    db: # PostgreSQL + pgvector
      image: pgvector/pgvector:pg16
      container_name: postgres_service
      ports:
        - "5432:5432"           # 호스트 5432 → 컨테이너 5432
      volumes:
        - ./postgres_data:/var/lib/postgresql/data  # DB 데이터 영속 저장
      environment:
        - POSTGRES_DB=db_postgres
        - POSTGRES_USER=user_postgres
        - POSTGRES_PASSWORD=pwd_postgres
